auth:
 credentials:
   username: ${INSTA_USER}
   password: ${INSTA_PASS}

limits:
 interactions:
   max_daily: 150

 relationship_bounds:
   max_followers: 12000
   min_followers: 800
   min_following: 400
   min_posts: 15
   max_following: 20000
   max_posts: 800

schedule:
 active_hours:
   weekday:
     morning:
       start: "07:45"
       end: "11:15"
     lunch:
       start: "12:15"
       end: "13:15"
     evening:
       start: "18:30"
       end: "23:30"
   weekend:
     start: "10:30"
     end: "23:50"

 breaks:
   bathroom:
     morning:
       hour_start: 9
       hour_end: 10
     afternoon:
       hour_start: 15
       hour_end: 16
     evening:
       hour_start: 19
       hour_end: 20
     duration:
       min: 240
       max: 720
   lunch:
     hour_start: 12
     hour_end: 14
     duration:
       min: 2400
       max: 4500

targeting:
 locations:
   - '213829509/sao-paulo-brazil/'
   - '213670729/rio-de-janeiro-brazil/'
   - '214494743/curitiba-parana/'
   - '213949389/campinas-sao-paulo/'

 hashtags:
   work:
     - programacao
     - desenvolvedor
     - tecnologia
     - javascript
     - python
     - reactjs
   interest:
     - coding
     - programadorweb
     - programadorbackend
     - fullstack
     - devops
     - datascience
   lifestyle:
     - vidadev
     - programadorlifestyle
     - tech

 accounts:
   - github
   - stackoverflow
   - microsoft
   - awscloud
   - googledevs
   - pythonbrasil
   - rocketseat_oficial
   - aluraonline

engagement:
 hourly_limits:
   sleepy:
     follows: 2
     unfollows: 1
     likes: 5
     comments: 0
   normal:
     follows: 4
     unfollows: 3
     likes: 10
     comments: 1
   active:
     follows: 6
     unfollows: 4
     likes: 15
     comments: 2
